repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # isort - Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # flake8 - Linting and style checking
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.7.0
          - flake8-import-order==0.18.2
          - flake8-bugbear==24.8.19

  # mypy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports]

  # bandit - Security linting
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [--skip, "B101,B601"]

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Check for debugger imports and py37+ breakpoint() calls
      - id: debug-statements
      # Check for files with names that would conflict on a case-insensitive filesystem
      - id: check-added-large-files
        args: [--maxkb=500]
      # Trim trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Make sure files end in a newline and only a newline
      - id: end-of-file-fixer
      # Check for valid JSON
      - id: check-json
      # Check for valid YAML
      - id: check-yaml
        args: [--allow-multiple-documents]
      # Check for valid TOML
      - id: check-toml
      # Prevent giant files from being committed
      - id: check-added-large-files

  # Check Python AST
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast

  # Dockerfile linting (if needed for Python containerization)
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile*